#! /bin/bash

set -e
set -u

if [[ $# -ne 1 ]] ; then
    echo "Usage: $0 <shader-id-or-url>" >&2
    exit 1
fi

BASEDIR="$(dirname "$0")"
SHADER_ID="$1"

GS_RE="^(http://(www\.)?glslsandbox\.com/e#)?[0-9]+\.[0-9]+$"
ST_RE="^(https?://(www\.)?shadertoy\.com/view/)?[0-9a-zA-Z]{6}$"

DL_PREFIX=""

if grep -Eq "${GS_RE}" <<< "${SHADER_ID}" ; then
    DL_PREFIX="gs"
elif grep -Eq "${ST_RE}" <<< "${SHADER_ID}" ; then
    DL_PREFIX="st"
else
    echo "ERROR: Shader identifier or URL not recognized" >&2
    exit 1
fi

exec "${BASEDIR}/${DL_PREFIX}-dl-shader" "${SHADER_ID}"
