#! /bin/bash

set -e
set -u

if [[ $# -ne 2 ]] ; then
    echo "Usage: $0 <shader.list> <file.frag>" >&2
    exit 1
fi

SHADER_LIST="$1"
FRAGFILE="$2"
FRAGSTR="${FRAGFILE%.frag}"
FRAG_NICK="$(grep -E "^${FRAGSTR}[[:blank:]]" "${SHADER_LIST}" | sed -r 's/^([0-9]+\.[0-9]+|[0-9a-zA-Z]{6})[[:blank:]]+//')"

if [[ -z "${FRAG_NICK}" ]] ; then
    FRAG_NICK="${FRAGSTR}"
fi

GS_RE="^(http://(www\.)?glslsandbox\.com/e#)?[0-9]+\.[0-9]+$"
ST_RE="^(https?://(www\.)?shadertoy\.com/view/)?[0-9a-zA-Z]{6}$"

SHADER_KIND="SHADER_UNKNOWN"

if grep -Eq "${GS_RE}" <<< "${FRAGSTR}" ; then
    SHADER_KIND="SHADER_GLSLSANDBOX"
elif grep -Eq "${ST_RE}" <<< "${FRAGSTR}" ; then
    SHADER_KIND="SHADER_SHADERTOY"
else
    echo "ERROR: Shader identifier type not recognized" >&2
    exit 1
fi

echo "  {"
echo "    ${SHADER_KIND}, \"${FRAGSTR}\", \"${FRAG_NICK}\","

sed -r \
    -e 's/\\/\\\\/g' \
    -e 's/"/\\"/g' \
    -e 's/^/"/' \
    -e 's/$/\\n"/' \
    "${FRAGFILE}"

echo "  },"
