#! /bin/bash

set -e
set -u

if [[ $# -ne 2 ]] ; then
    echo "Usage: $0 <shader.list> <file.frag>" >&2
    exit 1
fi

SHADER_LIST="$1"
FRAGFILE="$2"
FRAGSTR="${FRAGFILE%.frag}"
FRAG_NICK="$(grep -E "^${FRAGSTR}[[:blank:]]" "${SHADER_LIST}" | sed -r 's/^([0-9]+\.[0-9]+|[0-9a-zA-Z]{6})[[:blank:]]+//')"

if [[ -z "${FRAG_NICK}" ]] ; then
    FRAG_NICK="${FRAGSTR}"
fi

echo "  {"
echo "    \"${FRAGSTR}\", \"${FRAG_NICK}\","

sed -r \
    -e 's/\\/\\\\/g' \
    -e 's/"/\\"/g' \
    -e 's/^/"/' \
    -e 's/$/\\n"/' \
    "${FRAGFILE}"

echo "  },"
